### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by MouseUser** [Largequantityofcheese/The-Grand-Quandale-Hotel#1]
make the code work please

**Comment by GregFeetPics** [comment]
No, it its broken

**Comment by MouseUser** [comment]
listen, whatever your selling, i aint buying yo

**Comment by GregFeetPics** [comment]
Well, my name is Skylar White yo.

**Comment by GregFeetPics** [comment]
My husband is Walter White. Yo

**Comment by GregFeetPics** [comment]
Uh huh

**Comment by GregFeetPics** [comment]
He told me everything

**Comment by MouseUser** [comment]
seriously?

**Comment by GregFeetPics** [comment]
That's right.

**Comment by GregFeetPics** [comment]
L+Can't keep me from commenting+Ratio+No Men
